name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  GOOS: linux
  GOARCH: amd64
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run make
      run: make build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
        path: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        tag_name: $(TAG)
        release_name: Release $(TAG)
        draft: false
        prerelease: false
        artifacts: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
