name: Build and Release

on:
  push:
    branches:
      - main
env:
  GOOS: linux
  GOARCH: amd64
  NEW_TAG: v1.0.0
  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run make
      run: make build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
        path: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Use Automatic Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        tag_name: $(NEW_TAG)
        assets: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
        release_name: Release $(NEW_TAG)
        repo_token: ${{ GITHUB_TOKEN }}
        draft: false
        prerelease: false
