name: Build and Release

on:
  push:
    branches:
      - main

env:
  GOOS: linux
  GOARCH: amd64
  NEW_TAG: "${{ steps.version.outputs.new_version }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Generate version number
      id: version
      uses: thiagoaraujodev/action-version-bump@v1.1.0
      with:
        version_file: version.txt
        type: patch

    - name: Run make
      run: make build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
        path: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false
        artifacts: iRobo_${{ env.GOOS }}_${{ env.GOARCH }}
